import type { Metadata } from "next";
import { Quicksand, Dancing_Script } from 'next/font/google'
import './globals.css'

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400', '700'], // light, normal, bold
  variable: '--font-quicksand',
})

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // normal, medium, bold
  variable: '--font-dancing-script',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${quicksand.variable} ${dancingScript.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}